// -WARNING-DO NOT EDIT THIS FILE ⚠️

import { Injectable } from '@angular/core';
import { InMemoryDbService } from 'angular-in-memory-web-api';
import Course from '../types/course.model';
import Student from '../types/student.model';

@Injectable({
  providedIn: 'root',
})
export class InMemoryDataService implements InMemoryDbService {
  createDb(): {
    courses: Course[];
    students: Student[];
  } {
    return {
      courses: [
        {
          id: 1,
          courseName: 'English 1',
          creditHours: 3.0,
        },
        {
          id: 2,
          courseName: 'English 2',
          creditHours: 3.0,
        },
        {
          id: 3,
          courseName: 'English 3',
          creditHours: 3.0,
        },
        {
          id: 4,
          courseName: 'AP English',
          creditHours: 3.0,
        },
        {
          id: 5,
          courseName: 'Algebra 1',
          creditHours: 4.0,
        },
        {
          id: 6,
          courseName: 'Geometry',
          creditHours: 4.0,
        },
        {
          id: 7,
          courseName: 'Algebra 2',
          creditHours: 4.0,
        },
        {
          id: 8,
          courseName: 'Statistics',
          creditHours: 3.0,
        },
        {
          id: 9,
          courseName: 'Calculus',
          creditHours: 4.0,
        },
        {
          id: 10,
          courseName: 'Biology',
          creditHours: 4.0,
        },
        {
          id: 11,
          courseName: 'Chemistry',
          creditHours: 4.0,
        },
        {
          id: 12,
          courseName: 'Anatomy',
          creditHours: 4.0,
        },
        {
          id: 13,
          courseName: 'Geology',
          creditHours: 4.0,
        },
        {
          id: 14,
          courseName: 'Art 1',
          creditHours: 3.0,
        },
        {
          id: 15,
          courseName: 'Art 2',
          creditHours: 3.0,
        },
        {
          id: 16,
          courseName: 'Choir',
          creditHours: 3.0,
        },
        {
          id: 17,
          courseName: 'Band',
          creditHours: 3.0,
        },
        {
          id: 18,
          courseName: 'Theater',
          creditHours: 3.0,
        },
        {
          id: 19,
          courseName: 'European History',
          creditHours: 3.0,
        },
        {
          id: 20,
          courseName: 'American History',
          creditHours: 3.0,
        },
        {
          id: 21,
          courseName: 'African History',
          creditHours: 3.0,
        },
        {
          id: 22,
          courseName: 'Middle Eastern History',
          creditHours: 3.0,
        },
        {
          id: 23,
          courseName: 'Asian History',
          creditHours: 3.0,
        },
      ],
      students: [
        {
          id: 1,
          firstName: 'Carlita',
          lastName: 'Charon',
          classYear: '2025',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 2,
          firstName: 'Deborah',
          lastName: 'Lowing',
          classYear: '2027',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 3,
          firstName: 'Rennie',
          lastName: 'Fitzjohn',
          classYear: '2026',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 4,
          firstName: 'Pam',
          lastName: 'Ellicott',
          classYear: '2024',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 5,
          firstName: 'Gisella',
          lastName: 'Daveren',
          classYear: '2028',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 6,
          firstName: 'Hazlett',
          lastName: 'Wickson',
          classYear: '2027',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 7,
          firstName: 'Jaquelin',
          lastName: 'Van Halen',
          classYear: '2025',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 8,
          firstName: 'Loralyn',
          lastName: 'Casaccia',
          classYear: '2027',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 9,
          firstName: 'Hailey',
          lastName: 'Aiton',
          classYear: '2027',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 10,
          firstName: 'Melonie',
          lastName: 'McAdam',
          classYear: '2024',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 11,
          firstName: 'Jewelle',
          lastName: 'Jelley',
          classYear: '2028',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 12,
          firstName: 'Lynnet',
          lastName: 'Kemmish',
          classYear: '2023',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 13,
          firstName: 'Dulci',
          lastName: 'Lamblot',
          classYear: '2023',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 14,
          firstName: 'Marilin',
          lastName: 'Keeney',
          classYear: '2025',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 15,
          firstName: 'Zena',
          lastName: 'Tenpenny',
          classYear: '2028',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 16,
          firstName: 'Chiquita',
          lastName: 'Hustler',
          classYear: '2028',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 17,
          firstName: 'Marleen',
          lastName: 'Blizard',
          classYear: '2024',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 18,
          firstName: 'Fletcher',
          lastName: 'Tomczynski',
          classYear: '2023',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 19,
          firstName: 'Rozina',
          lastName: 'Fardon',
          classYear: '2023',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 20,
          firstName: 'Dyanne',
          lastName: 'Rourke',
          classYear: '2024',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 21,
          firstName: 'Dorrie',
          lastName: 'Rigolle',
          classYear: '2023',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 22,
          firstName: 'Jocelyne',
          lastName: 'Walak',
          classYear: '2023',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 23,
          firstName: 'Bartlet',
          lastName: 'Heare',
          classYear: '2027',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 24,
          firstName: 'Osgood',
          lastName: 'Otley',
          classYear: '2026',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 25,
          firstName: 'Sergeant',
          lastName: 'Hartmann',
          classYear: '2023',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 26,
          firstName: 'Trudy',
          lastName: 'Bonett',
          classYear: '2025',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 27,
          firstName: 'Lauri',
          lastName: 'Coggeshall',
          classYear: '2028',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 28,
          firstName: 'Cecily',
          lastName: 'Brandsma',
          classYear: '2024',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 29,
          firstName: 'Esra',
          lastName: 'Langrish',
          classYear: '2024',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 30,
          firstName: 'Clemens',
          lastName: 'Kalb',
          classYear: '2025',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 31,
          firstName: 'Denys',
          lastName: 'Hysom',
          classYear: '2024',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 32,
          firstName: 'Fleurette',
          lastName: 'Galletley',
          classYear: '2024',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 33,
          firstName: 'Annabel',
          lastName: 'Snow',
          classYear: '2028',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 34,
          firstName: 'Elwin',
          lastName: 'Truss',
          classYear: '2023',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 35,
          firstName: 'Sheila',
          lastName: 'Orange',
          classYear: '2026',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 36,
          firstName: 'Marci',
          lastName: 'Crutchfield',
          classYear: '2026',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 37,
          firstName: 'Corrie',
          lastName: 'Raistrick',
          classYear: '2027',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 38,
          firstName: 'Randell',
          lastName: 'Shilstone',
          classYear: '2026',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 39,
          firstName: 'Pammie',
          lastName: 'De Brett',
          classYear: '2027',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 40,
          firstName: 'Devy',
          lastName: 'Rozec',
          classYear: '2028',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 41,
          firstName: 'Desiri',
          lastName: 'Muddle',
          classYear: '2027',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 42,
          firstName: 'Eal',
          lastName: 'Morphew',
          classYear: '2026',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 43,
          firstName: 'Molli',
          lastName: 'Dudliston',
          classYear: '2026',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 44,
          firstName: 'Noble',
          lastName: 'Sandilands',
          classYear: '2024',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 45,
          firstName: 'Gaelan',
          lastName: 'Ferrillo',
          classYear: '2028',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 46,
          firstName: 'Emogene',
          lastName: 'Josefson',
          classYear: '2028',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 47,
          firstName: 'Kerrin',
          lastName: 'Colrein',
          classYear: '2025',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 48,
          firstName: 'Maure',
          lastName: 'Bartrap',
          classYear: '2023',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 49,
          firstName: 'Israel',
          lastName: 'Hacker',
          classYear: '2028',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
        {
          id: 50,
          firstName: 'Baudoin',
          lastName: 'Crooks',
          classYear: '2023',
          get fullName(): string {
            return `${this.firstName} ${this.lastName}`;
          },
        },
      ],
    };
  }

  genId(data: Course[] | Student[]): number {
    // If data is empty, use 1 as id.
    // If not, use the last id + 1 as id.
    // Allow `id` to be `undefined` by just using `0` in the `map`.
    return data.length > 0 ? Math.max(...data.map((d) => d.id || 0)) + 1 : 1;
  }
}
