// -WARNING-DO NOT EDIT THIS FILE ⚠️

import { Injectable } from '@angular/core';
import { InMemoryDbService } from 'angular-in-memory-web-api';
import Player from '../types/player.model';

@Injectable({
  providedIn: 'root',
})
export class InMemoryDataService implements InMemoryDbService {
  createDb(): {
    players: Player[];
  } {
    return {
      players: [
        {
          id: 5,
          name: 'Randall',
          phone: '555-555-Evil',
          email: 'codeWizard@dnd.com',
          city: 'Cleveland',
        },
      ],
    };
  }

  genId(data: Player[]): number {
    // If data is empty, use 1 as id.
    // If not, use the last id + 1 as id.
    // Allow `id` to be `undefined` by just using `0` in the `map`.
    return data.length > 0 ? Math.max(...data.map((d) => d.id || 0)) + 1 : 1;
  }
}
